Repository SWYP-team-2th/client, pull requests merged in 2025-02, with the labels that each got.

#44 스토리북 초기 환경 세팅
  .github/workflows/storybook-build-check.yml
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/components/__tests__/templates/Component.stories.tsx
  src/components/__tests__/templates/Component.template.tsx
  yarn.lock
Labels: chore

#45 MSW 초기 세팅
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  yarn.lock
Labels: chore

#47 build.sh 파일과 원격 레포 push 워크플로우를 추가한다.
  .github/workflows/git-push.yml
  build.sh
  yarn.lock
Labels: chore

#49 git push yml 파일을 수정한다.
  .github/workflows/git-push.yml
Labels: fix

#50 prod, dev 배포 워크플로우 작성
  .github/workflows/git-deploy.yml
Labels: chore

#51 develop 브랜치 deploy 오타 수정
  .github/workflows/git-deploy.yml
Labels: chore

#52 Revert "develop 브랜치 deploy 오타 수정"
  .github/workflows/git-deploy.yml
Labels: chore

#55 Vercel에 스토리북 배포를 하기 위한 세팅을 한다.
  build.sh
  package.json
  vercel.json
Labels: chore

#60 Icon 공통 컴포넌트를 제작한다.
  src/assets/icons/alert_fill_24px.svg
  src/assets/icons/alert_outline_24px.svg
  src/assets/icons/arrow_left_24px.svg
  src/assets/icons/arrow_right_24px.svg
  src/assets/icons/bell_fill_24px.svg
  src/assets/icons/bell_outline_24px.svg
  src/assets/icons/bookmark_fill_24px.svg
  src/assets/icons/bookmark_outline_24px.svg
  src/assets/icons/check_24px.svg
  src/assets/icons/cross_24px.svg
  src/assets/icons/edit_24px.svg
  src/assets/icons/heart_fill_24px.svg
  src/assets/icons/heart_outline_24px.svg
  src/assets/icons/home_fill_24px.svg
  src/assets/icons/home_outline_24px.svg
  src/assets/icons/link_24px.svg
  src/assets/icons/lock_fill_24px.svg
  src/assets/icons/lock_open_24px.svg
  src/assets/icons/lock_outline_24px.svg
  src/assets/icons/maximize_24px.svg
  src/assets/icons/menu_24px.svg
  src/assets/icons/message_fill_24px.svg
  src/assets/icons/message_outline_24px.svg
  src/assets/icons/minimize_24px.svg
  src/assets/icons/minus_24px.svg
  src/assets/icons/more_24px.svg
  src/assets/icons/photo_plus_24px.svg
  src/assets/icons/plus_24px.svg
  src/assets/icons/post_24px.svg
  src/assets/icons/search_fill_24px.svg
  src/assets/icons/search_outline_24px.svg
  src/assets/icons/send_24px.svg
  src/assets/icons/settings_fill_24px.svg
  src/assets/icons/settings_outline_24px.svg
  src/assets/icons/thumb-up_fill_24px.svg
  src/assets/icons/thumb-up_outline_24px.svg
  src/assets/icons/trash_24px.svg
  src/assets/icons/user2_fill_24px.svg
  src/assets/icons/user2_outline_24px.svg
  src/assets/icons/user_fill_24px.svg
  src/assets/icons/user_outline_24px.svg
  src/assets/icons/world_24px.svg
  src/components/common/Icon/Icon.stories.tsx
  src/components/common/Icon/Icon.tsx
  src/components/common/Icon/index.ts
  src/index.css
Labels: feature

#62 design token custom
  src/index.css
  tailwind.config.js
Labels: feature

#69 layout setting
  src/components/common/layout/DefaultLayout.tsx
  src/components/common/layout/SubLayout.tsx
  tailwind.config.js
Labels: feature

#73 디자인 시스템 변경 사항 반영
  src/index.css
  tailwind.config.js
Labels: feature

#74 버튼 컴포넌트를 제작한다.
  package.json
  src/components/common/button/Button.tsx
  src/components/common/button/FloatingButton.tsx
  yarn.lock
Labels: feature

#76 라우터 구조 설정 및 기본 레이아웃 적용
  src/components/common/layout/DefaultLayout.tsx
  src/components/common/layout/SubLayout.tsx
  src/main.tsx
  src/pages/onboarding/OnBoardingPage.tsx
  src/pages/post/PostPage.tsx
  src/routes/routing.tsx
Labels: feature

#77 헤더 컴포넌트를 제작한다.
  src/assets/icons/logo.svg
  src/components/common/Button/Button.tsx
  src/components/common/Button/FloatingButton.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Icon/Icon.tsx
  src/components/common/Layout/DefaultLayout.tsx
  src/components/common/Layout/SubLayout.tsx
  src/pages/OnBoarding/OnBoardingPage.tsx
  src/pages/Post/PostPage.tsx
  src/routes/routing.tsx
Labels: feature

#84 추가된 버튼 디자인에 대응한다.
  src/components/common/Button/FloatingButton.tsx
Labels: feature

#85 TextField 컴포넌트를 작성한다.
  src/components/common/TextField/TextField.stories.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/TextField/index.ts
  src/components/common/TextInput/TextInput.stories.tsx
  src/components/common/TextInput/TextInput.tsx
  src/components/common/TextInput/index.ts
  src/index.css
Labels: feature

#88 추가된 Icon에 대응 및 size option을 추가한다.
  src/assets/icons/alert_V2.svg
  src/assets/icons/heart_fill_Red.svg
  src/assets/icons/vote_close.svg
  src/components/common/Icon/Icon.tsx
Labels: feature

#89 Toast 컴포넌트를 작성한다.
  src/assets/icons/toast_error.svg
  src/assets/icons/toast_info.svg
  src/assets/icons/toast_success.svg
  src/assets/icons/toast_warning.svg
  src/components/common/Icon/Icon.tsx
  src/components/common/Toast/Toast.stories.tsx
  src/components/common/Toast/Toast.tsx
  src/components/common/Toast/ToastProvider.tsx
  src/components/common/Toast/hooks.ts
  src/components/common/Toast/index.ts
  src/components/common/Toast/types.ts
  src/main.tsx
Labels: feature

#91 VotePage 화면 디자인을 구현한다.
  src/App.tsx
  src/assets/icons/medal.svg
  src/components/common/Icon/Icon.tsx
  src/components/vote-detail/Comment/CommentItem.tsx
  src/components/vote-detail/Comment/CommentList.tsx
  src/components/vote-detail/Comment/CommentSection.tsx
  src/components/vote-detail/Input/CommentInput.tsx
  src/components/vote-detail/Top/VoteAuthorInfo.tsx
  src/components/vote-detail/Top/VoteTopSection.tsx
  src/components/vote-detail/Top/VoteVerticalEllipsis.tsx
  src/components/vote-detail/Vote/VoteCardItem.tsx
  src/components/vote-detail/Vote/VoteCardList.tsx
  src/components/vote-detail/Vote/VoteResultItem.tsx
  src/components/vote-detail/Vote/VoteResultList.tsx
  src/components/vote-detail/Vote/VoteSection.tsx
  src/pages/ Vote/VotePage.tsx
  src/pages/Post/PostPage.tsx
  src/routes/routing.tsx
Labels: feature

#95 온보딩 페이지 UI를 구현한다.
  src/App.tsx
  src/pages/OnBoarding/OnBoardingPage.tsx
Labels: feature

#93 Dialog 컴포넌트를 작성한다.
  src/components/common/Dialog/Dialog.stories.tsx
  src/components/common/Dialog/Dialog.tsx
  src/components/common/Dialog/DialogProvider.tsx
  src/components/common/Dialog/hooks.ts
  src/components/common/Dialog/index.ts
  src/components/common/Overlay/Overlay.tsx
  src/components/common/Overlay/index.ts
  src/main.tsx
Labels: feature

#100 설정 페이지를 작성한다.
  src/assets/icons/logout.svg
  src/components/common/Dialog/Dialog.tsx
  src/components/common/Icon/Icon.tsx
  src/components/common/Layout/DefaultLayout.tsx
  src/components/common/Layout/SubLayout.tsx
  src/components/common/Toast/ToastProvider.tsx
  src/components/settings/LogoutDialog/LogoutDialog.tsx
  src/components/settings/LogoutDialog/index.ts
  src/components/settings/Menu/Menu.tsx
  src/components/settings/Menu/index.ts
  src/components/settings/hooks.tsx
  src/pages/settings/SettingsPage.tsx
  src/routes/routing.tsx
Labels: feature

#106 마이페이지를 구현한다.
  src/api/config.ts
  src/api/useGetUserInfo.ts
  src/api/useGetVoteList.ts
  src/assets/gif/spinner.gif
  src/components/common/Loading/Loading.tsx
  src/components/common/Loading/index.ts
  src/components/common/Overlay/Overlay.tsx
  src/components/my/Profile/Profile.tsx
  src/components/my/Profile/VoteList/MyVoteList/MyVoteList.tsx
  src/components/my/Profile/VoteList/MyVoteList/hooks.ts
  src/components/my/Profile/VoteList/MyVoteList/index.ts
  src/components/my/Profile/VoteList/ParticipatedVoteList/ParticipatedVoteList.tsx
  src/components/my/Profile/VoteList/ParticipatedVoteList/hooks.ts
  src/components/my/Profile/VoteList/ParticipatedVoteList/index.ts
  src/components/my/Profile/VoteList/Tab/Tab.tsx
  src/components/my/Profile/VoteList/Tab/constants.ts
  src/components/my/Profile/VoteList/Tab/index.ts
  src/components/my/Profile/VoteList/VoteList.tsx
  src/components/my/Profile/VoteList/index.ts
  src/components/my/Profile/hooks.ts
  src/components/my/Profile/index.ts
  src/pages/my/MyPage.tsx
  src/routes/routing.tsx
  src/types/pageable.ts
Labels: feature

#101 라벨 컴포넌트를 작성한다.
  src/assets/icons/medal_fill_white.svg
  src/components/common/Icon/Icon.tsx
  src/components/common/Label/Label.tsx
Labels: feature

#104 투표 올리기 페이지를 작성한다.
  src/components/common/Button/Button.tsx
  src/components/common/TextField/TextField.tsx
  src/components/vote-regist/FieldContainer/FieldContainer.tsx
  src/components/vote-regist/FieldContainer/index.ts
  src/components/vote-regist/Provider/VoteRegistProvider.tsx
  src/components/vote-regist/Provider/hooks.ts
  src/components/vote-regist/VoteDescription/VoteDescription.tsx
  src/components/vote-regist/VoteDescription/hooks.ts
  src/components/vote-regist/VoteDescription/index.ts
  src/components/vote-regist/VoteImages/ImageUploader/ImageUploader.tsx
  src/components/vote-regist/VoteImages/ImageUploader/hooks.ts
  src/components/vote-regist/VoteImages/ImageUploader/index.ts
  src/components/vote-regist/VoteImages/PreviewImage/PreviewImage.tsx
  src/components/vote-regist/VoteImages/PreviewImage/index.ts
  src/components/vote-regist/VoteImages/VoteImages.tsx
  src/components/vote-regist/VoteImages/index.ts
  src/components/vote-regist/VoteRegistForm/VoteRegistForm.tsx
  src/components/vote-regist/VoteRegistForm/hooks.ts
  src/components/vote-regist/VoteRegistForm/index.ts
  src/components/vote-regist/constants.ts
  src/pages/ Vote/VoteRegistPage.tsx
  src/routes/routing.tsx
Labels: feature

#119 헤더 스타일을 변경한다.
  src/components/common/Header/Header.tsx
Labels: fix

#112 BottomSheet 컴포넌트를 제작한다.
  src/components/common/BottomSheet/BottomSheet.stories.tsx
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/BottomSheet/BottomSheetProvider.tsx
  src/components/common/BottomSheet/hooks.ts
  src/components/common/BottomSheet/index.ts
  src/main.tsx
Labels: feature

#125 로그인 성공 후 uerId 절대값으로 설정한다.
  src/pages/Login/OAuthPage.tsx
Labels: feature

#114 카카오톡 링크 공유, URL 복사 로직을 작성한다.
  index.html
  src/api/useKakaoShareUrl.ts
  src/components/common/LinkShareBottomSheet/LinkShareBottomSheet.tsx
  src/components/common/LinkShareBottomSheet/hooks.ts
  src/components/common/LinkShareBottomSheet/index.ts
  src/types.d.ts
Labels: feature

#127 로그인 버튼 클릭 시 redirectURI 절대 경로 설정
  src/components/login/button/LoginButton.tsx
Labels: fix

#129 dev환경에서 API 요청이 운영서버로 가는 이슈를 해결한다.
  src/api/config.ts
Labels: fix

#131 토큰에 추가된 userId를 반영하여 로그인 성공 시 유저 고유의 마이페이지로 리다이렉트 한다.
  src/api/config.ts
  src/api/useGetIdentificationInfo.ts
  src/api/usePostKaKaoLogin.ts
  src/pages/Login/OAuthPage.tsx
Labels: feature

#122 이미지 상세 모달을 제작한다.
  src/api/useGetVoteDetail.ts
  src/components/common/Dialog/DialogProvider.tsx
  src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx
  src/components/vote-detail/ImageDetailModal/hooks.ts
  src/components/vote-detail/ImageDetailModal/index.ts
  src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
  src/components/vote-detail/Vote/VoteSection/VoteSection.tsx
Labels: feature

#143 댓글 페이지네이션을 구현한다.
  src/api/useAddComment.ts
  src/api/useGetComment.ts
  src/components/comment-detail/CommentList/CommentList.tsx
  src/components/comment-detail/CommentList/index.ts
  src/components/comment-detail/hooks.ts
  src/components/vote-detail/Comment/CommentList/CommentList.tsx
  src/components/vote-detail/Comment/CommentList/hooks.ts
  src/components/vote-detail/Comment/CommentSection/CommentSection.tsx
  src/components/vote-detail/Comment/CommentSection/hooks.ts
  src/components/vote-detail/Comment/CommentSection/index.ts
  src/components/vote-detail/Input/CommentInput.tsx
  src/components/vote-detail/Vote/VoteSection/VoteSection.tsx
  src/pages/Vote/VoteCommentDetailPage.tsx
  src/pages/Vote/VotePage.tsx
  src/routes/routing.tsx
Labels: feature

#144 투표 마감 시 베스트픽 처리한다.
  src/api/useGetVoteDetail.ts
  src/api/useGetVoteStatus.ts
  src/api/useVote.ts
  src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/CloseConfirmDialog.tsx
  src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/hooks.ts
  src/components/vote-detail/Top/ViteVerticalEllipsis/hooks.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
  src/components/vote-detail/Vote/VoteCard/hooks.ts
Labels: feature
