Repository SWYP-team-2th/client, pull requests merged in 2025-03, with the labels that each got.

#154 온보딩 페이지 구현
  package.json
  src/assets/images/onboarding/onboarding1.png
  src/assets/images/onboarding/onboarding2.png
  src/assets/images/onboarding/onboarding3.png
  src/constants/onboarding.ts
  src/pages/OnBoarding/OnBoardingPage.tsx
  yarn.lock
Labels: feature

#148 메뉴 버튼이 작성자일 때만 노출하도록 수정한다.
  src/api/useGetVoteDetail.ts
  src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
Labels: feature

#156 플로팅 버튼 위치가 상이한 문제, 상세 컨텐츠가 잘리는 문제를 해결한다.
  src/components/common/Dialog/DialogProvider.tsx
  src/components/common/Layout/DefaultLayout.tsx
  src/pages/Vote/VotePage.tsx
Labels: fix

#157 리다이렉트 로직 작성한다.
  src/App.tsx
  src/api/useGetMyInfo.ts
  src/routes/routing.tsx
Labels: fix

#158 마이페이지에 zero ui를 추가한다.
  src/assets/images/my/no-my-vote-list.png
  src/assets/images/my/no-participated-vote-list.png
  src/components/common/Layout/SubLayout.tsx
  src/components/common/Loading/Loading.tsx
  src/components/my/Profile/Profile.tsx
  src/components/my/Profile/VoteList/MyVoteList/MyVoteList.tsx
  src/components/my/Profile/VoteList/ParticipatedVoteList/ParticipatedVoteList.tsx
  src/components/my/Profile/VoteList/VoteList.tsx
  src/pages/my/MyPage.tsx
Labels: feature

#165 미반영된 온보딩 디자인을 반영한다.
  src/pages/OnBoarding/OnBoardingPage.tsx
Labels: fix

#167 운영 카카오 관련 키값을 반영한다.
  src/api/useKakaoShareUrl.ts
  src/components/login/button/LoginButton.tsx
  src/utils/cn/getEnvironment.ts
Labels: feature

#174 배포 환경 플래그 값을 잘못 참조하고 있는 것을 수정한다.
  src/api/config.ts
  src/utils/cn/getEnvironment.ts
Labels: fix

#177 투표 마감시 컨펌 메세지를 수정한다.
  src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/CloseConfirmDialog.tsx
  src/components/vote-detail/Top/ViteVerticalEllipsis/hooks.tsx
Labels: fix

#187 게스트 투표에도 로딩을 추가한다.
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
Labels: fix

#192 공통 컴포넌트들의 변경 사항에 모두 대응한다.
  src/assets/icons/filter.svg
  src/assets/icons/home-filled.svg
  src/assets/icons/home.svg
  src/assets/icons/home_fill_24px.svg
  src/assets/icons/home_outline_24px.svg
  src/assets/icons/talk.svg
  src/assets/icons/vote.svg
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Icon/Icon.tsx
  src/components/common/LinkShareBottomSheet/LinkShareBottomSheet.tsx
  src/components/common/TextField/TextField.tsx
  src/components/common/Toast/Toast.tsx
  tailwind.config.js
Labels: fix

#197 온보딩 페이지 QA에 대응한다.
  src/assets/images/onboarding/onboarding1.png
  src/assets/images/onboarding/onboarding2.png
  src/assets/images/onboarding/onboarding3.png
  src/components/common/Loading/Loading.tsx
  src/index.css
  src/pages/Login/OAuthPage.tsx
  src/pages/OnBoarding/OnBoardingPage.tsx
  src/pages/my/MyPage.tsx
Labels: fix

#201 투표 게시글 페이지 QA에 대응한다.
  src/components/common/BottomSheet/BottomSheet.tsx
  src/components/common/Dialog/Dialog.tsx
  src/components/common/Header/Header.tsx
  src/components/common/LinkShareBottomSheet/LinkShareBottomSheet.tsx
  src/components/vote-detail/Comment/CommentItems/CommentItem.tsx
  src/components/vote-detail/Comment/CommentList/CommentList.tsx
  src/components/vote-detail/Input/CommentInput.tsx
  src/components/vote-detail/Top/ViteVerticalEllipsis/CloseConfirmDIalog/CloseConfirmDialog.tsx
  src/components/vote-detail/Top/ViteVerticalEllipsis/hooks.tsx
  src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
  src/components/vote-detail/Vote/VoteResult/VoteResultItem.tsx
  src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx
  src/pages/NotFound/NotFoundPage.tsx
  src/pages/Vote/VoteCommentDetailPage.tsx
  src/pages/Vote/VotePage.tsx
  src/pages/my/MyPage.tsx
  src/pages/settings/SettingsPage.tsx
  tailwind.config.js
Labels: fix

#203 버튼 디자인 추가 대응
  src/components/common/Button/Button.tsx
  src/pages/my/MyPage.tsx
Labels: feature

#207 화면 축소 시 온보딩 Pagenation dot과 하단 버튼이 겹치는 상황에 대응한다.
  src/constants/onboarding.ts
  src/pages/OnBoarding/OnBoardingPage.tsx
Labels: fix

#205 바텀 네비게이션을 구현한다.
  src/assets/icons/post_white.svg
  src/components/common/Icon/Icon.tsx
  src/components/common/Layout/DefaultLayout.tsx
  src/components/common/Navigation/Navigation.tsx
  src/components/common/Navigation/hooks.tsx
  src/pages/Home/Home.tsx
  src/routes/routing.tsx
Labels: feature

#220 switch 컴포넌트를 제작한다.
  src/components/common/Switch/Switch.stories.tsx
  src/components/common/Switch/Switch.tsx
  src/components/common/Switch/index.ts
  src/index.css
Labels: feature

#216 추가된 라벨 컴포넌트에 대응한다.
  src/components/common/Label/AnimatedLabel.tsx
  src/components/common/Label/Label.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx
  tailwind.config.js
Labels: feature

#232 카카오 관련 환경변수를 통일한다.
  src/api/useKakaoShareUrl.ts
  src/components/login/button/LoginButton.tsx
  src/hooks/useKakaoLogin.ts
Labels: chore

#223 투표 올리기 2차 MVP 반영 및 디자인 수정
  src/api/usePostRegistVote.ts
  src/components/common/Button/Button.tsx
  src/components/common/RadioButton/RadioGroup.tsx
  src/components/common/RadioGroup/RadioGroup.tsx
  src/components/vote-regist/FieldContainer/FieldContainer.tsx
  src/components/vote-regist/Provider/VoteRegistProvider.tsx
  src/components/vote-regist/VoteImages/ImageUploader/ImageUploader.tsx
  src/components/vote-regist/VoteImages/ImageUploader/hooks.ts
  src/components/vote-regist/VoteImages/VoteImages.tsx
  src/components/vote-regist/VoteRegistForm/VoteRegistForm.tsx
  src/components/vote-regist/VoteRegistForm/hooks.ts
  src/components/vote-regist/VoteScope/VoteScope.tsx
  src/components/vote-regist/VoteScope/index.ts
  src/components/vote-regist/VoteType/VoteType.tsx
  src/components/vote-regist/VoteType/index.ts
  src/components/vote-regist/constants.ts
  src/pages/Vote/VoteRegistPage.tsx
Labels: feature

#225 이미지 상세 모달 2차 MVP 반영한다.
  src/api/useGetVoteDetail.ts
  src/components/common/Dialog/Dialog.tsx
  src/components/common/Dialog/DialogProvider.tsx
  src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx
  src/components/vote-detail/ImageDetailModal/hooks.ts
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
Labels: feature

#238 투표 취소 기능을 구현한다.
  src/api/useCancelVoted.ts
  src/api/useGetMyInfo.ts
  src/api/useGetVoteDetail.ts
  src/api/useGetVoteStatus.ts
  src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
  src/components/vote-detail/Vote/VoteCard/hooks.ts
  src/components/vote-detail/Vote/VoteResult/hooks.ts
Labels: feature

#234 홈페이지를 UI 구현한다.
  src/assets/icons/message-outline-gray.svg
  src/assets/icons/vote-gray.svg
  src/components/common/Icon/Icon.tsx
  src/components/home/HomeImages/ImageItem.tsx
  src/components/home/HomeImages/ImageList.tsx
  src/components/home/HomeImages/hooks.ts
  src/components/home/HomeImages/index.ts
  src/components/home/HomeInfo/HomeInfo.tsx
  src/components/home/HomeInfo/hooks.ts
  src/components/home/HomeInfo/index.ts
  src/components/home/HomeSection/HomeSection.tsx
  src/components/home/HomeSection/hooks.ts
  src/components/home/HomeSection/index.ts
  src/components/home/HomeTaskCheck/HomeTaskCheck.tsx
  src/components/home/HomeTaskCheck/hooks.ts
  src/components/home/HomeTaskCheck/index.ts
  src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
  src/components/vote-detail/ViteVerticalEllipsis/CloseConfirmDIalog/CloseConfirmDialog.tsx
  src/components/vote-detail/ViteVerticalEllipsis/CloseConfirmDIalog/hooks.ts
  src/components/vote-detail/ViteVerticalEllipsis/CloseConfirmDIalog/index.ts
  src/components/vote-detail/ViteVerticalEllipsis/DeleteConfirmDialog/DeleteConfirmDialog.tsx
  src/components/vote-detail/ViteVerticalEllipsis/DeleteConfirmDialog/hooks.ts
  src/components/vote-detail/ViteVerticalEllipsis/DeleteConfirmDialog/index.ts
  src/components/vote-detail/ViteVerticalEllipsis/VoteVerticalEllipsis.tsx
  src/components/vote-detail/ViteVerticalEllipsis/hooks.tsx
  src/components/vote-detail/ViteVerticalEllipsis/index.ts
  src/pages/Home/Home.tsx
Labels: feature

#236 투표 게시글 페이지 2차 MVP에 대응한다.
  src/api/useDeleteComment.ts
  src/api/useGetComment.ts
  src/api/useUpdateComment.ts
  src/assets/icons/pencil-gray.svg
  src/assets/icons/trash-can-gray.svg
  src/components/comment-detail/CommentList/CommentList.tsx
  src/components/common/Icon/Icon.tsx
  src/components/vote-detail/Comment/CommentItems/CommentItem.tsx
  src/components/vote-detail/Comment/CommentList/CommentList.tsx
  src/components/vote-detail/Comment/DeleteCommentDialog/DeleteCommentDialog.tsx
  src/components/vote-detail/Comment/DeleteCommentDialog/hooks.ts
  src/components/vote-detail/Comment/DeleteCommentDialog/index.ts
  src/components/vote-detail/Input/CommentInput.tsx
  src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
  src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx
  src/pages/Vote/VoteCommentDetailPage.tsx
  src/pages/Vote/VotePage.tsx
Labels: feature

#242 투표 현황의 더보기 버튼을 구현한다.
  src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx
  src/components/vote-detail/Vote/VoteResult/hooks.ts
Labels: feature

#248 투표 취소 API 호출 시 투표 API가 함께 호출되지 않도록 반영한다.
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
Labels: fix

#249 투표 결과가 반영되지 않는 문제를 해결한다.
  src/components/vote-detail/Vote/VoteCard/VoteCardItem.tsx
  src/components/vote-detail/Vote/VoteCard/VoteCardList.tsx
  src/components/vote-detail/Vote/VoteCard/hooks.ts
Labels: fix

#245 닉네임 클릭 시 해당 닉네임을 유저의 마이페이지로 이동하는 커스텀 훅을 제작한다.
  src/hooks/useNicknameNavigation.tsx
Labels: feature

#250 홈 페이지 API를 연동한다.
  src/api/useGetFeed.ts
  src/components/home/HomeImages/ImageItem.tsx
  src/components/home/HomeImages/ImageList.tsx
  src/components/home/HomeInfo/HomeInfo.tsx
  src/components/home/HomeSection/HomeSection.tsx
  src/components/home/HomeTaskCheck/HomeTaskCheck.tsx
  src/components/vote-detail/Comment/CommentItems/CommentItem.tsx
  src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
  src/hooks/useNicknameNavigation.tsx
  src/pages/Home/Home.tsx
Labels: feature

#258 타 유저의 사진 투표 전 투표 유도 이미지가 안 보이는 상황을 해결한다.
  src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx
Labels: fix

#262 피드 API 호출 관련 QA를 반영한다.
  src/components/home/HomeImages/ImageList.tsx
  src/components/home/hooks.ts
Labels: fix

#260 2차 MVP QA 페이지 이동을 설정한다.
  src/pages/Home/Home.tsx
  src/pages/Login/OAuthPage.tsx
  src/pages/NotFound/NotFoundPage.tsx
  src/pages/Vote/VoteCommentDetailPage.tsx
  src/pages/Vote/VotePage.tsx
  src/pages/my/MyPage.tsx
Labels: feature

#267 바텀 네비게이션이 컨텐츠 가리는 문제를 해결한다.
  src/components/common/Layout/DefaultLayout.tsx
Labels: fix

#268 토큰 유무에 따른 라우팅 경로를 설정한다.
  src/components/common/Navigation/hooks.tsx
  src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/OAuthPage.tsx
  src/pages/NotFound/NotFoundPage.tsx
  src/pages/OnBoarding/OnBoardingPage.tsx
  src/pages/Vote/VoteCommentDetailPage.tsx
  src/pages/my/MyPage.tsx
  src/routes/routing.tsx
Labels: fix

#271 알림 버튼 클릭 시 토스트를 제공한다.
  src/components/home/HomeImages/ImageItem.tsx
  src/components/home/HomeImages/ImageList.tsx
  src/components/home/HomeInfo/HomeInfo.tsx
  src/components/home/HomeSection/HomeSection.tsx
  src/components/vote-detail/Top/VoteAuthorInfo/VoteAuthorInfo.tsx
  src/components/vote-detail/Top/VoteTopSection/VoteTopSection.tsx
  src/components/vote-detail/Top/VoteTopSection/index.ts
  src/pages/Home/Home.tsx
  src/pages/Vote/VotePage.tsx
Labels: fix

#274 사진 확대 시 상단 사진배열 너비 고정후 드래그 하게 할 수 있도록 수정한다.
  src/components/vote-detail/ImageDetailModal/ImageDetailModal.tsx
Labels: fix

#276 비회원이 기본 도메인 접근 시 onboarding으로 가도록 한다.
  src/pages/Home/Home.tsx
Labels: fix

#278 피드백 주기 메뉴를 추가한다.
  src/components/settings/hooks.tsx
Labels: feature

#282 온보딩 페이지 접속 시 스플레쉬 페이지를 추가한다.
  src/assets/images/splash/Splash.png
  src/pages/OnBoarding/OnBoardingPage.tsx
Labels: feature

#288 설정 페이지 내부 아이콘, 텍스트를 수정한다.
  src/assets/icons/logout_gray.svg
  src/assets/icons/right_arrow_gray.svg
  src/components/common/Icon/Icon.tsx
  src/components/settings/Menu/Menu.tsx
  src/components/settings/hooks.tsx
Labels: fix

#286 해당 게시글의 Author일 시 투표 현황을 항상 보여준다.
  src/components/vote-detail/Vote/VoteResult/VoteResultList.tsx
  src/components/vote-detail/Vote/VoteResult/hooks.ts
Labels: fix

#292 투표 결과 바 UI를 개선한다.
  src/components/vote-detail/Vote/VoteResult/VoteResultItem.tsx
Labels: fix

#294 투표 디테일 페이지 헤더 로고 클릭 시 경로를 수정한다.
  src/pages/Vote/VotePage.tsx
Labels: fix

#308 피드백 링크 도메인을 수정한다.
  src/components/settings/hooks.tsx
Labels: fix
